.PHONY: clean All

All:
	@echo "----------Building project:[ source - Debug ]----------"
	@"$(MAKE)" -f  "source.mk"
clean:
	@echo "----------Cleaning project:[ source - Debug ]----------"
	@"$(MAKE)" -f  "source.mk" clean
